const Product=require('../models/Product');
const Category=require('../models/Category');
const homepage=require('../config/homepage');
const settings=require('../config/settings');
const {escapeRegex,metaDescription}=require('../utils/text');
const {automaticMetaTitle}=require('../utils/storefront');

async function categories(){const rows=await Category.find({isActive:true}).sort({name:1}).lean();return rows.map(c=>({...c,parentId:null,children:[],depth:0,descendantSlugs:[c.slug],image:'',description:''}));}
function decorate(p,categoryMap){const v=p.variants?.[0]||{weight:'Standard',price:0,stock:0};const cat=categoryMap.get(p.category);return {...p,categoryName:cat?.name||p.category,categoryIcon:cat?.icon||p.emoji||'📦',price:Number(v.price||0),stock:Number(v.stock||0),displayWeight:'Standard',variantLabel:'Option',details:p.desc,status:Number(v.stock||0)>0?'active':'out'};}
async function allProducts(){const [rows,cats]=await Promise.all([Product.find({isActive:true}).sort({createdAt:-1}).lean(),categories()]);const map=new Map(cats.map(c=>[c.slug,c]));return {products:rows.map(p=>decorate(p,map)),cats,map};}
function summary(products,cats){const out={all:products.length};cats.forEach(c=>out[c.slug]=products.filter(p=>p.category===c.slug).length);return out;}

async function home(req,res,next){try{const {products,cats}=await allProducts();const featured=products.slice(0,homepage.featuredProducts.limit);const sections=['hero','trustBar','categories','featuredProducts','process','promo'].filter(k=>homepage[k]?.enabled!==false).map(key=>({key}));return res.render('public/pages/home',{active:'home',cartCount:0,homepage,homepageSections:sections,homeCategories:cats,featuredProducts:featured,categorySummary:summary(products,cats),metaTitle:settings.seo.metaTitle,metaDesc:settings.seo.metaDescription,canonical:null,breadcrumbs:[]});}catch(e){next(e);}}

async function productsPage(req,res,next){try{const {products,cats}=await allProducts();const q=String(req.query.q||req.query.search||'').trim().slice(0,100);const requested=String(req.params.slug||req.query.category||'').trim().toLowerCase();const selected=cats.find(c=>c.slug===requested)||null;let filtered=products;if(selected)filtered=filtered.filter(p=>p.category===selected.slug);if(q){const needle=q.toLowerCase();filtered=filtered.filter(p=>`${p.name} ${p.desc} ${p.categoryName}`.toLowerCase().includes(needle));}const max=Math.max(1,...products.map(p=>Number(p.price||0)));const pageName=selected?selected.name:'Products';return res.render('public/pages/products',{active:'products',cartCount:0,products:filtered,categories:cats,currentCategory:selected?.slug||'all',categorySummary:summary(products,cats),totalProducts:filtered.length,priceMax:Math.ceil(max),searchQuery:q,metaTitle:automaticMetaTitle(pageName,settings.store.name),metaDesc:selected?`Browse ${selected.name} products from ${settings.store.name}.`:`Browse products from ${settings.store.name}.`,canonical:null,breadcrumbs:[]});}catch(e){next(e);}}

async function detail(req,res,next){try{const cats=await categories();const map=new Map(cats.map(c=>[c.slug,c]));const row=await Product.findOne({slug:req.params.slug,isActive:true}).lean();if(!row)return res.status(404).render('public/pages/not-found',{title:'Product not found',metaDesc:'The requested product could not be found.',cartCount:0,active:'products'});const product=decorate(row,map);const relatedRows=await Product.find({isActive:true,category:product.category,_id:{$ne:row._id}}).sort({createdAt:-1}).limit(4).lean();const relatedProducts=relatedRows.map(p=>decorate(p,map));return res.render('public/pages/detail',{active:'products',cartCount:0,product,relatedProducts,categoryPath:`/products/category/${product.category}`,metaTitle:automaticMetaTitle(product.name,settings.store.name),metaDesc:metaDescription(product.desc,product.name),canonical:null,breadcrumbs:[]});}catch(e){next(e);}}

async function cart(req,res,next){try{return res.render('public/pages/cart',{active:'cart',cartCount:0,canonical:null,breadcrumbs:[]});}catch(e){next(e);}}
async function checkout(req,res,next){try{return res.render('public/pages/checkout',{active:'cart',cartCount:0,cartItems:[],cartSummary:{subtotal:0,shipping:0,total:0},customer:null,canonical:null,breadcrumbs:[]});}catch(e){next(e);}}
async function policies(req,res,next){try{return res.render('public/pages/policies',{active:'policies',cartCount:0,canonical:null,breadcrumbs:[]});}catch(e){next(e);}}
async function search(req,res,next){try{const q=String(req.query.q||'').trim().slice(0,80);if(!q)return res.json({products:[]});const rx=new RegExp(escapeRegex(q),'i');const cats=await categories();const map=new Map(cats.map(c=>[c.slug,c]));const rows=await Product.find({isActive:true,$or:[{name:rx},{desc:rx}]}).sort({createdAt:-1}).limit(8).lean();return res.json({products:rows.map(p=>decorate(p,map)).map(p=>({id:p.id,name:p.name,slug:p.slug,desc:p.desc,category:p.category,categoryName:p.categoryName,emoji:p.emoji,images:p.images,price:p.price}))});}catch(e){next(e);}}
module.exports={home,productsPage,detail,cart,checkout,policies,search,categories,decorate};
